### ISSUE TITLE
Use asym key to sign webhooks

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/example-config-service#1]
If https://github.com/woodpecker-ci/woodpecker/pull/916 lands, this repo need some adjustments ...

@s00500 your feedback would be welcome there too ;)

**Comment by s00500** [comment]
This looks like a great change, I can update the repo on the weekend if I find a bit of time

**Comment by s00500** [comment]
Ok if you are on it already :-)

**Comment by 6543** [comment]
ok it got merged :)

**Comment by s00500** [comment]
Nice work!

**Comment by anbraten** [comment]
Thanks, also for your initial work 😉. I am so excited for https://github.com/woodpecker-ci/woodpecker/pull/915 which will allow us to configure extensions (like config, secrets & registry service) on a per repo base.
