### ISSUE TITLE
Issue with key

### ISSUE THREAD

**Issue by s00500** [woodpecker-ci/example-config-service#3]
For some reason I cant make this work... when I fetch the key I get a file with 
-----BEGIN PUBLIC KEY-----
base64 string
-----END PUBLIC KEY-----

This will not load with hex.DecodeString

I tried decoding the base64 before but only get an invalid key length error later....

What have I misunderstood ?

**Comment by anbraten** [comment]
@s00500 Are you using github.com/go-ap/httpsig? We switched the lib at the time we changed to using a publik key?

**Comment by s00500** [comment]
Yes I do, just copied the verification part from the updated example... but I am unsure how the public key needs to be formated

**Comment by s00500** [comment]
Ok, so to make it work I took a look at the encoding part in woodpacker and properly reversed it so that the file can be used just as is when it gets fetched from the API

```
	pubKeyRaw, err := ioutil.ReadFile(pubKeyPath)
	if err != nil {
		log.Fatal("Failed to read public key file")
	}

	pemblock, _ := pem.Decode(pubKeyRaw)

	b, err := x509.ParsePKIXPublicKey(pemblock.Bytes)
	if err != nil {
		log.Fatal("Failed to parse public key file ", err)
	}
	pubKey, ok := b.(ed25519.PublicKey)
	if !ok {
		log.Fatal("Failed to parse public key file")
	}
```

This seems to work,
If you can confirm that I did not misunderstand anything I will modify the example here too, I can also add the http fetch for the publickey if you want me to :-)

**Comment by 6543** [comment]
@s00500 if it works, just create a pull :)

**Comment by s00500** [comment]
done :-)
