### ISSUE TITLE
Bump httpsig version

### ISSUE THREAD

**Issue by s00500** [woodpecker-ci/example-config-service#5]
seems like the httpsig package needs an update.... 
It broke for me when I updated woody server today and I had to update the package in the config service too to get it back to work...
also the repo has ben archived by the owner... I can do that later this week...

**Comment by pinpox** [comment]
The dependency seems to be unmaintained, which is a bit troublesome for something security-related. Are there any alternatives or plans to migrate it?

**Comment by pinpox** [comment]
I'll look into it. I based my configurator on this example and it's working for now, but I plan to use it for longer so I'll see if I can find something maintained

**Comment by 6543** [comment]
done ... and a pull to migrate to a new lib is proposed:  #10
