### ISSUE TITLE
Link to web docs broken in readme

### ISSUE THREAD

**Issue by gedw99** [woodpecker-ci/example-config-service#6]
https://woodpecker-ci.org/docs/administration/external-configuration-api Is 404

need to update the Readme.md

**Comment by 6543** [comment]
https://woodpecker-ci.org/docs/next/administration/external-configuration-api

**Comment by pinpox** [comment]
The docs are released now. This can be closed, the link now works

**Comment by 6543** [comment]
@pinpox wana send a pull?

**Comment by 6543** [comment]
Uh sorry ... should have read it twice :)
