### ISSUE TITLE
CONFIG_SERVICE_SECRET is unused

### ISSUE THREAD

**Issue by pinpox** [woodpecker-ci/example-config-service#8]
I don't see any mention of CONFIG_SERVICE_SECRET in the code. Is this variable deprecated, can it be removed?

**Comment by 6543** [comment]
yes

**Comment by 6543** [comment]
as we now use public key to verify

**Comment by 6543** [comment]
@pinpox I can not find any reference to `CONFIG_SERVICE_SECRET` ... where did you pick it up or can we close this issue?

**Comment by pinpox** [comment]
It's at least in the .env.example.

**Comment by 6543** [comment]
closed by 030a8077a69b857ebea390fb8a4610a655d1667c
